version: '3.3'

services:

  server:
      depends_on:
        - mongo
      build: ./server
      container_name: server
      command: npm start
      ports:
        - "8080:8080"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
  client_web:
    depends_on:
      - mongo
    build: ./webapp
    container_name: webapp
    command: npm start
    ports:
     - "8081:8081"
#  mobile_user:
#    depends_on:
#      - server
#      - client_web
#    build: ./mobile
#    container_name: mobile
#    command: expo build:android
volumes:
  data-volume: